title: Effect Reducer
description: React.useReducer hook on steroids with the possibility of side-effects controlling
baseurl: "/rescript-effect-reducer" # the subpath of your site, e.g. /blog
url: "https://vaclavhrach.github.io"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil
theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
