// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function single(action, dispatch) {
  return Curry._1(dispatch, action);
}

function delayed(action, delay, dispatch) {
  setTimeout((function (param) {
          return Curry._1(dispatch, action);
        }), delay);
  
}

function batch(actions, dispatch) {
  return Belt_Array.forEach(actions, Curry.__1(dispatch));
}

export {
  single ,
  delayed ,
  batch ,
  
}
/* No side effect */
