// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function signle(effect, dispatch) {
  return Curry._1(effect, dispatch);
}

function delayed(effect, delay, dispatch) {
  setTimeout((function (param) {
          return Curry._1(effect, dispatch);
        }), delay);
  
}

function batch(effects, dispatch) {
  return Belt_Array.forEach(effects, (function (effect) {
                return Curry._1(effect, dispatch);
              }));
}

export {
  signle ,
  delayed ,
  batch ,
  
}
/* No side effect */
