// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useEffectReducer(param) {
  var update = param.update;
  var match = React.useReducer((function (param, action) {
          return Curry._2(update, param[0], action);
        }), param.init);
  var rest = match[0];
  var effect = rest[1];
  var dispatch = match[1];
  React.useEffect((function () {
          Curry._1(effect, dispatch);
          
        }), [rest]);
  return [
          rest[0],
          dispatch
        ];
}

var Effect;

export {
  Effect ,
  useEffectReducer ,
  
}
/* react Not a pure module */
